In [35]:
#Create RNN model to analyze the stock prices
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten,Conv2D,Dense,LSTM,Embedding

In [84]:
df=pd.read_csv('Google_Stock_Price_Train.csv')

In [85]:
df

Date    Open    High     Low   Close      Volume
0       1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1       1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2       1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3       1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4       1/9/2012  322.04  322.29  309.46  620.76  11,688,800
...          ...     ...     ...     ...     ...         ...
1253  12/23/2016  790.90  792.74  787.28  789.91     623,400
1254  12/27/2016  790.68  797.86  787.66  791.55     789,100
1255  12/28/2016  793.70  794.23  783.20  785.05   1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79     744,300
1257  12/30/2016  782.75  782.78  770.41  771.82   1,770,000

[1258 rows x 6 columns]

In [86]:
#Eliminate commas in the close dataset
df['Close']=df['Close'].str.replace(',','').astype(float)

In [87]:
train_set=df.iloc[:,4:5].values
train_set

array([[663.59],
       [666.45],
       [657.21],
       ...,
       [785.05],
       [782.79],
       [771.82]])

In [88]:
#The data is in 2D array format
# The RNN expects the data to be scaled.
#That means we have to fit the data in between some values like 0 to 1.
# This can be done by using MinMax Scaler

In [89]:
train_set=sc.fit_transform(train_set)
train_set

array([[0.23757287],
       [0.24151427],
       [0.22878051],
       ...,
       [0.40495845],
       [0.40184391],
       [0.38672602]])

In [90]:
train_set.shape

(1258, 1)

In [91]:
# Now we can take X_train data starting from 0th row onwards from the train_set.
#We can take y_train data (predicted price),starting from 1st row onwards.
X_train=train_set[0:1257]
y_train=train_set[1:1258]

In [92]:
print('enter the X_train values :',X_train)
print('enter the y_train values :' ,y_train)

enter the X_train values : [[0.23757287]
 [0.24151427]
 [0.22878051]
 ...
 [0.41391618]
 [0.40495845]
 [0.40184391]]
enter the y_train values : [[0.24151427]
 [0.22878051]
 [0.21641884]
 ...
 [0.40495845]
 [0.40184391]
 [0.38672602]]


In [93]:
#As the RNN model aspects the 3D data,We have to reshape the X_train data into 3D.
#This indicates 1257= rows
#1column
#1 timestep
#Timestep indicates the frequency of data : 1 day
import numpy as np
X_train=np.reshape(X_train,(1257,1,1))

# Building the RNN Model

In [95]:
#units=50 means 50 nodes
#return_sequences=True means it is going to return same number of outputs to the next layer.
#input_shape=(None,1) means only 1 column of data is being given as input
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential([LSTM(units=50,return_sequences=True,input_shape=(None,1)),
                  LSTM(units=50,return_sequences=True),Dense(1,activation='sigmoid')])

# Compile the RNN model

In [66]:
model.compile(optimizer='adam',loss='mean_squared_error')

# Train the Model

In [67]:
model.fit(X_train,y_train,epochs=100,batch_size=10)

Epoch 1/100
126/126 [==============================] - 4s 2ms/step - loss: 0.0610
Epoch 2/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0129
Epoch 3/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0015
Epoch 4/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 5/100
126/126 [==============================] - 0s 3ms/step - loss: 0.0014
Epoch 6/100
126/126 [==============================] - 1s 9ms/step - loss: 0.0014
Epoch 7/100
126/126 [==============================] - 1s 4ms/step - loss: 0.0014
Epoch 8/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 9/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 10/100
126/126 [==============================] - 0s 3ms/step - loss: 0.0014
Epoch 11/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 12/100
126/126 [==============================] - 0s 2ms/step - loss: 0.0014
Epoch 13/100


# Making predictions

In [112]:
test_set=pd.read_csv('Google_Stock_Price_Test.csv')
test_set.head()

Date    Open    High     Low   Close     Volume
0  1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1  1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2  1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3  1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4  1/9/2017  806.40  809.97  802.83  806.65  1,272,400

In [113]:
test_set=test_set.iloc[:,4:5].values
test_set

array([[786.14],
       [786.9 ],
       [794.02],
       [806.15],
       [806.65],
       [804.79],
       [807.91],
       [806.36],
       [807.88],
       [804.61],
       [806.07],
       [802.17],
       [805.02],
       [819.31],
       [823.87],
       [835.67],
       [832.15],
       [823.31],
       [802.32],
       [796.79]])

In [118]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler()
inputs=sc.fit(test_set)
inputs=sc.transform(test_set)

In [121]:
inputs

array([[0.        ],
       [0.01534424],
       [0.1590955 ],
       [0.40399758],
       [0.41409247],
       [0.37653947],
       [0.4395316 ],
       [0.40823743],
       [0.4389259 ],
       [0.37290531],
       [0.40238239],
       [0.32364224],
       [0.38118312],
       [0.66969513],
       [0.76176055],
       [1.        ],
       [0.92893196],
       [0.75045427],
       [0.3266707 ],
       [0.2150212 ]])

In [123]:
#The above data is in the form of 2D array ,So convert it into 3D array
inputs=np.reshape(inputs,(20,1,1))
inputs

array([[[0.        ]],

       [[0.01534424]],

       [[0.1590955 ]],

       [[0.40399758]],

       [[0.41409247]],

       [[0.37653947]],

       [[0.4395316 ]],

       [[0.40823743]],

       [[0.4389259 ]],

       [[0.37290531]],

       [[0.40238239]],

       [[0.32364224]],

       [[0.38118312]],

       [[0.66969513]],

       [[0.76176055]],

       [[1.        ]],

       [[0.92893196]],

       [[0.75045427]],

       [[0.3266707 ]],

       [[0.2150212 ]]])

In [126]:
pred_values=model.predict(inputs)
pred_values

1/1 [==============================] - 1s 1s/step


array([[[0.5       ]],

       [[0.500004  ]],

       [[0.50003976]],

       [[0.50009304]],

       [[0.500095  ]],

       [[0.50008756]],

       [[0.50009996]],

       [[0.5000939 ]],

       [[0.50009984]],

       [[0.5000868 ]],

       [[0.5000927 ]],

       [[0.5000766 ]],

       [[0.5000885 ]],

       [[0.50013936]],

       [[0.50015265]],

       [[0.50017977]],

       [[0.50017273]],

       [[0.5001511 ]],

       [[0.5000772 ]],

       [[0.50005275]]], dtype=float32)

In [130]:
#the model is nothing but 3D array that contains scaled data.
#Let us convert it into 2D as:
pred_values=np.reshape(pred_values,(20,1))
pred_values

array([[0.5       ],
       [0.500004  ],
       [0.50003976],
       [0.50009304],
       [0.500095  ],
       [0.50008756],
       [0.50009996],
       [0.5000939 ],
       [0.50009984],
       [0.5000868 ],
       [0.5000927 ],
       [0.5000766 ],
       [0.5000885 ],
       [0.50013936],
       [0.50015265],
       [0.50017977],
       [0.50017273],
       [0.5001511 ],
       [0.5000772 ],
       [0.50005275]], dtype=float32)

In [157]:
pred_values.shape

(20, 1)

# inverse_transform method

In [158]:
#it is bassically used to reverse the scaled data to obtain the normal data.
#NOTE:--------->
#this method takes the data in the form of 2D array
#Thats why we have changed the data from 3D to 2D .
test_pred=sc.inverse_transform(pred_values)
test_pred

array([[810.90497],
       [810.9052 ],
       [810.9069 ],
       [810.9096 ],
       [810.90967],
       [810.9093 ],
       [810.91   ],
       [810.90967],
       [810.91   ],
       [810.9093 ],
       [810.9096 ],
       [810.9088 ],
       [810.9094 ],
       [810.9119 ],
       [810.91254],
       [810.91394],
       [810.9136 ],
       [810.91254],
       [810.9088 ],
       [810.9076 ]], dtype=float32)

# Predicting the next day stock price

In [175]:
today_price=float(input('enter the today stockprice: '))

enter the today stockprice: 1500


In [176]:
arr=np.array(today_price).reshape(-1,1)
arr1=sc.transform(arr)

In [177]:
arr1

array([[14.41267918]])

In [178]:
arr1=arr1.reshape(-1,1,1)
result=model.predict(arr1)

1/1 [==============================] - 0s 19ms/step


In [179]:
result=np.reshape(result,(1,1))

In [180]:
#this is the scaled data.
#Inverse scaling is needed to see the original values.
#this can be done by using inverse_transform() function
tom_price=sc.inverse_transform(result)

In [181]:
tom_price

array([[810.57495]], dtype=float32)

In [182]:
#this can be understand that the stockmarket price is increased for the next day