In [48]:
import tensorflow as tf

# Constant Tensor

In [49]:
#'tf.string': String type of data
#'tf.float': Float type of data
#'tf.integer': integer type of data

In [50]:
 #For constant Function ,we should use constant() function
c1=tf.constant(10)

In [51]:
c2=tf.constant('hello world')
c2

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

# Variable Tensor

In [52]:
tf.Variable(25)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=25>

# Creating Tensor with Arrays

In [53]:
#Create a 1-d array with 4 elements
arr1=tf.constant([[10,11,12],[20,21,22]])
arr1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [20, 21, 22]])>

In [54]:
arr3=tf.Variable([[[10,11,12],[20,21,22],[30,31,32],[40,41,42]]])
arr3

<tf.Variable 'Variable:0' shape=(1, 4, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32],
        [40, 41, 42]]])>

In [55]:
arr3.name

'Variable:0'

In [56]:
arr3.shape

TensorShape([1, 4, 3])

# Using tensorflow ,add 2 numbers and display their sum.

In [64]:
import tensorflow as tf 

In [75]:
c=tf.add(a,b)
c 

<tf.Tensor: shape=(), dtype=float32, numpy=35.0>

In [76]:
#Now the run above graph(operation) in the session
sess=tf.compat.v1.Session() 

In [77]:
output = sess.run(c)  

RuntimeError: The Session graph is empty. Add operations to the graph before calling run().

In [62]:
import tensorflow as tf

# Define two constants as TensorFlow tensors
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0, dtype=tf.float32)

# Add the two constants and store the result in a third tensor
c = a + b

# Initialize a TensorFlow session and run the calculation
with tf.Session() as sess:
  result = sess.run(c)
  print(result)

AttributeError: module 'tensorflow' has no attribute 'Session'

In [63]:
X=tf.compat.v1.placeholder(tf.float32)
y=tf.compat.v1.placeholder(tf.float32)

RuntimeError: tf.placeholder() is not compatible with eager execution.

In [80]:
import tensorflow as tf
print(tf.__version__)
# Construct a `Session` to execute the graph.
with tf.compat.v1.Session() as sess:

  # Build a dataflow graph.
    a=tf.constant(10.0),
    b=tf.constant(25.0)
    c=tf.add(a,b)
  
# Execute the graph and store the value that `e` represents in `result`.
    result = sess.run(c)
    print(result) 

2.10.1
[35.]
